---
abstract: 'Simple stubbing for Mango to allow unit tests for code that uses it'
author:
  - 'J Gregory <john@johngregory.me.uk>'
build_requires:
  Test::Exception: 0.32
  Test::More: 0.99
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mock-Mango
no_index:
  directory:
    - t
    - inc
requires:
  Mango: 0.17
version: v0.01.1
